### PR TITLE
Option to show Waypoints over whole map / new format of Waytag

### PR DESCRIPTION
**Pull request by MalikShr**
- "Always Show Waypoints" Option (default: disabled)
- New class WaypointObjectMeta to store World Object data for waypoints.
- New listener GameTickListener to automatically update WaypointObjectMeta for each waypoint when necessary.
- Increased waypoint size to 1.5 times its original dimensions.
- Small changes in how Waypoints get build/ added/ removed
- Updated labyGradlePluginVersion to 0.3.28

### CODE REVIEW

**Comment by niklaswa** [comment]
Hey there, thanks for your contribution. Seems like you forgot to commit the Colors util class, would be nice if you could push this so that we can look into your changes :)

**Comment by MalikShr** [comment]
@niklaswa I added the Colors seems like I forgot it

**Comment by MalikShr** [comment]
I wantet to add, that iam not sure whether it would be better to release my changes as a standalone addon or to integrate them into the existing one. A possible name for this could be "WayTags.". But I would say, that this is your desicion.

**Comment by MalikShr** [comment]
> I wantet to add, that iam not sure whether it would be better to do some more changes and release my changes as a standalone addon or to integrate them into the existing one. A possible name for this could be "WayTags.". But I would say, that this is your desicion.

I've found some bugs in my code, which is why I closed this pull request. However, I would still appreciate hearing your opinion regarding my changes and whether they should be integrated into this addon or if it would be better to create a separate one. I am planning to add more features, such as dimension and world-specific waypoint loading.

**Pull request closed without merging**
